on:
  workflow_dispatch:
    inputs:
      workflow_name:
        required: false

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/callable-workflow.yaml