on:
  workflow_dispatch:
    inputs:
      workflow_name:
        required: false

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
    
  call:
    uses:  ./.github/workflows/callable-workflow.yaml
  
  dynamic-call:
    uses: ${{ inputs.workflow_name }}